#################################################################################################################################################

## Need to turn this into a proper function, but I was hoping someone might find this useful before I actually have time to do that.
## All of the objects here (e.g. dd2, drp) are objects assigned during the DADA2 pipeline. These are the names for the objects that they used
## and these are the names that I have stuck with since running the pipeline. Please change these objects to what you have named them. I don't believe
## any packages are required for this code, but let me know if you run into any problems!!!

###################################################################################################################################################
# Input the ASV string of interest. Right now this only works for one ASV
ASVoI <- ""

# Make a vector of your sample IDs here (you can do this however you want)
dd2_sample_ids <- basename(filts_nops_fns)

# create empty list
read_list <- list()

i <- NULL
iter <- NULL
for (i in dd2_sample_ids){
  # map reads
  read.map <- dd2[[i]]$map
  read.to.derep.sequence <- as.data.frame(drp[[i]]$uniques) %>%
    rownames_to_column(var="raw_read")
  # merge these into one object?
  read.map_w_seq <- do.call(rbind, Map(data.frame, raw_read=read.to.derep.sequence$raw_read, map_to_ASV=read.map))
  # get the ASVs found in sample i
  allASVs <- as.data.frame(dd2[[i]]$denoised) %>%
  rownames_to_column(var="ASV")
  
  for (denoised_asv in allASVs$ASV){
    iter <- 1
    if(denoised_asv == ASVoI) {
             map_num <- iter
             seq_vec <- read.map_w_seq %>%
               filter(., map_to_ASV == map_num) %>%
               select(raw_read) 
             read_list[[length(read_list)+1]] <- seq_vec
           }
    else {
           iter <- iter + 1
    }
  }
}

# calculate 'size' (num of reads total)
for (i in 1:length(read_list)){
  if(i==1){
    size <- length(read_list[[i]][["raw_read"]])
    total <- size
  }
  else{
    size <- length(read_list[[i]][["raw_read"]])
    total <- total + size
  }
}
